### PR TITLE
Haris Kapagioridis

### PR DESCRIPTION
**Pull request by akorolczuk**
Another test we received from Haris Kapagioridis

Link to whole project: https://drive.google.com/file/d/1t2J6htbdYvHvbjIPBPlHGsJ50f95YFgR/view?usp=sharing

### CODE REVIEW

**Comment by Moniraego** [comment]
OK having tried the game, I have to revise my opinion. The code is clean, but he didn't seem to focus on making it work at all, let alone making it good. Someone else should test it in case I'm missing something, but the gameplay wasn't just bad, it was totally broken. Did he leave a note like 'Sorry I wasn't able to finish it but anyway check out my code style'?

**Comment by akorolczuk** [comment]
I spoke with Haris and he's aware that he sent completely broken test. Here's what he said:

> The gameplay doesn’t work at all and in addition I didn’t complete more things for example presenter and properties are  initialised in the view instead of being more abstract.
> 
> To be completely honest I wasn’t seeing my self finishing in time and I was even thinking to drop it. If I wasn’t going to Greece I would have asked extra time for the weekend. 
> 
> Anyway I decided to spend more time on code structure and leave the gameplay at the end.
> 
> I don’t have expectations from the test cause I am aware of the incomplete state

**Comment by akorolczuk** [comment]
Tomorrow we're supposed to get a test from another candidate. We'll see what he came up with. Perhaps this is indeed too big of a task. Or Haris is not the guy we're looking for.

**Comment by Moniraego** [comment]
It is an interesting to see whether a candidate chooses a quick and easy game that works or the perfect version. This seems more like a workshop exercise to make people realise the futility of perfection, like the Kobayashi Maru :p
But yeah, we need to see how many candidates we miss out on before someone finishes it reasonably well.

**Comment by akorolczuk** [comment]
Haris is going to finish the test and we'll review it again.

**Pull request closed without merging**
