### PR TITLE
Senior Client Engineer - Reinhold Radick

### PR DESCRIPTION
**Pull request by akorolczuk**
Please note: reviewing this is not mandatory but if you'd like to participate in PR everyone's welcome. 

Original repository here: https://gitlab.com/GottHold/tank-it-like-the-80s

### CODE REVIEW

**Comment by akorolczuk** [comment]
I don't think there's point of discussing the details here. Clearly not a senior level. Anyone disagrees?

**Comment by akorolczuk** [comment]
Ok so a bit of clarification - he's actually applying for Data Analyst but claims to have strong coding skills.. Sorry for confusion.

**Comment by Moniraego** [comment]
For senior client, a definite no. I'm not clear on what we want from our Data Analyst role. If it involves touching our client code more than a few lines, then no. If it's closer to game design but with the ability to code for statistical analysis or whatever, I'm not sure we can rule him our based on this. Have you seen how mathematicians code....

**Comment by dreamora** [comment]
For senior definitely no.

But: If he is applying as data analyst, why is he getting the Unity developer assignment in the first place?
Strong coder != can write even a line of game code ...

Wouldn't it have made sense to let him write decently complex multi nested join SQLs to see if he is capable of writing data analysis queries that do not instantly break our bank for example? (for that he would have had to work with Martin / Pat potentially > Playfab Insights)

Or something in Python / R processing a massive dump from a CSV (I guess Martin could provide that out of our Playfab Insights and that will without doubt have tons of data for this purpose as we generate several dozen million rows a day on Live) where data analysis takes place showing that he can deal with data at scale hw resource efficiently?
Python would probably be the better idea for us to evaluate as R is special while python while not being a C language is designed with ease of use in mind so it is straight forward to read for the most part.

**Comment by akorolczuk** [comment]
Quoting Martin:

"I was keen on him doing the test for two reasons:
1) he claimed to be a strong coder with a full suite of in/out game tools
developed (which I had doubts about)
2) if he wasn't that great but performed well in our test, we might have
needed to review our test ; )"

**Pull request closed without merging**
