### PR TITLE
Haris-Kapagioridis 2

### PR DESCRIPTION
**Pull request by akorolczuk**

### CODE REVIEW

**Comment by Moniraego** [comment]
Yeah I think this is very clean and not needlessly overcomplicated, but yeah slightly overkill for what is needed but a positive sign.
I wanted to run it but this time there is no link to the full project. Did he include that @akorolczuk?
I'm happy to interview him.

**Comment by akorolczuk** [comment]
Yeah I will email it to you

**Comment by Moniraego** [comment]
@akorolczuk Hmm, the look and feel is pretty rough, but it meets the specs I suppose.

**Comment by akorolczuk** [comment]
Yeah I think Haris strength could be UI, not essentially in game. So would
be great if another candidate had strong core game skills.

**Pull request closed without merging**
